### ISSUE TITLE
Plugin loads josm with wrong coordinates area

### ISSUE THREAD

**Issue by marcobra** [joto/qgis-plugin-osm-editor-remote-control#2]
In qgis i have project with epsg set to 3857 open on italy area if i try to load area i get Prague area loaded in Josm...
Coordinate system issue here...

Thank
Marco

**Comment by joto** [comment]
This works for me. Can you provide some more information: Which version of QGIS are you using? What layer(s) do you have? What steps did you follow to load your layers?

**Comment by marcobra** [comment]
- qgis 2.6.1-Brighton on Ubuntu 14.04 64bits
- i have a shape layer EPSG:4326 the project EPSG:3857 project  "On the Fly” reprojection  on
- simply opening shape layer it show good with the underlaying OpenStreetMap 

in another pc home pc (qgis 2.6.1-Brighton)  with a shp point layer (EPSG:4326) the project EPSG:3857 project, with  "On the Fly” reprojection on
i have the plugin icon grayed, reinstalling plugin not solve.

Thanks

**Comment by marcobra** [comment]
Is the custom layer projection the problem here... ?

**Comment by Skippern** [comment]
QGIS 2.18 on Mac OS X 10.11.6, all co-ordinates opens at 0.0N 0.0E, seems like the the coordinate variables are not set.

**Comment by joto** [comment]
This plugin is deprecated and will not work with QGIS version 3.
Use the QuickOSM plugin instead, it also has a "JOSM" button.
