### ISSUE TITLE
Button is greyed out

### ISSUE THREAD

**Issue by Nate-Wessel** [joto/qgis-plugin-osm-editor-remote-control#7]
I just installed this plugin in QGIS 2.14.17, and have JOSM version 12921 running on my Ubuntu desktop. The button was added to the menu bar, but is greyed out and can't be clicked. I've tried restarting, zooming in, etc. but can't get the button to become available.

**Comment by Nate-Wessel** [comment]
The button seems to have activated itself at some point, but I'm not sure when or how.

**Comment by joto** [comment]
You have to be zoomed in far enough. This might also not work correctly depending on the projection used in the map or if there are several layers with different projections and on-the-fly reprojection. I am not sure myself how QGIS is handling this.
