### ISSUE TITLE
I can't find the button or menu item at all, reinstall, appearing but greyed out.

### ISSUE THREAD

**Issue by TeAmigo** [joto/qgis-plugin-osm-editor-remote-control#9]
Using Qgis 2.18 on xUbuntu 16.04. I cannot find the button or menu item anywhere. Where is it hiding?
Thanks for your help.

**Comment by joto** [comment]
You have to zoom in to make the button usable.

**Comment by joto** [comment]
This plugin is deprecated and will not work with QGIS version 3.
Use the QuickOSM plugin instead, it also has a "JOSM" button.
